### ISSUE TITLE
Add flatpak support

### ISSUE THREAD

**Issue by FlorianUekermann** [Nitrokey/nitrokey-app#114]
Snap is pretty Ubuntu specific (and partly proprietary). Please add a flatpak package, since that seems to be where the rest of the Linux world is headed for distribution independent apps.

**Comment by szszszsz** [comment]
http://flatpak.org

**Comment by szszszsz** [comment]
Since the App is now integrated into most major distributions use of Snap or Flatpak loses on importance. Are there any special reasons for supporting it anyway?

**Comment by MaVo159** [comment]
Just ine example: The update frequency of this app is on a much shorter timescale than distributions release. This kind of decoupling from dists is why flatpak exists. In the long run you may even want to drop distribution packages.

**Comment by szszszsz** [comment]
App is updated through official repositories as usual package shortly after release and is managed by OS (Arch, Ubuntu, Fedora to name a few). There is no need to wait for next distribution release.
Is Flatpack: 
- Supported on Debian?
- Packages its dependencies with application?

The only practical use I see now is running it on distributions with old Qt library (hello stable Debian).
App is not really much in dynamically development when it would need a daily build. Stable releases were in past once a month at most.

**Comment by MaVo159** [comment]
That is not how many mainstream distribution​s update packages. There are often several years between releases and plenty of people end up running half a decade old releases at some point. Package repositories are not app stores, that is what snap and flatpak are for. After release many dists don't update packages, so once a month would outpace their frequency by a factor 40 or something like that.
Yes, all distributions I know of are working on support for flatpak and yes dependencies can be packaged. Also what about users of dists you dont have packages for?
Even support for new products that are not backwards compatible will become a problem.

**Comment by szszszsz** [comment]
I am not sure you know how the package update works. Distribution updates its own packages mainly and vendors/maintainers do their own. We have shipped v0.6.3 to Ubuntu (own PPA) and Fedora (main AFAIK) both 3 versions back without problems. I do not think the `frequency factor` example is real.
Let's talk concretely:
- What widely used distributions do you mean to be half-a-decade old? Debian, Centos? The latter is not supported by Flatpak because of old kernel anyway. The other ones would share similar issues probably.
- What backward compatibility problems do you mean?
- Are you sure Flatpak would not generate issues by itself? (Snap did)

It is true that we cannot support all distributions. I think most vendors can't. However large count are clones (sharing package or repository with mainline) and if someone use the original he/she is possibly a power user well accustomed to compiling applications. 
At least for the sake of Debian we could create such package (if it would make it work there).

**Comment by MaVo159** [comment]
I'm not following. You seem to have packages in official repos, so you don't control the release cycle. Let's make an example. After the freeze of the testing repo Debian releases after about 7 months and it usually takes about 24-30 months until the next release. That means people will use about 3 years old software at the end of a cycle. There is also little reason for some people to upgrade immediately, since LTS is supposed to last for at least 5 years, possibly much longer.
That means if you need to support a new firmware version that has interface changes (like the recent protocol change) or new hardware, people will need to install a new app from somewhere else than the official dist repo.
Many other dists work similarly, although the exact times may differ.

Also, maintaining all these packages is a lot of work, why would you want to do that in the long term? This app is exactly why snap and flatpak where invented (multiple reasons, not just updates).

It's nice to have packages for now, because flatpak support is just now becoming the norm. But for upcoming releases it gives you an easy way for cross dist releases.

Also don't forget that some people are just users, not admins. A great number of users can not install dist packages at work.

**Comment by jans23** [comment]
I suggest to focus on the next stable version 1.0 first. If we may face
a situation Florian is describing (outdated packages in distributions)
we should reconsider it from there.

**Comment by MaVo159** [comment]
Absolutely, this shouldn't be a priority, especially since a lot of people are not familiar with flatpak yet. Regarding outdated packages: Debian started the code freeze in February, so the next chance to get 1.0 into Debian stable is a couple of years away.

**Comment by szszszsz** [comment]
To investigate would using flatpack help to distribute App on Centos 6/7.
CC @techge

**Comment by techge** [comment]
As far as I can see neither [flatpack](http://flatpak.org/getting.html) nor [snapd](https://docs.snapcraft.io/core/install) support CentOS/RedHat yet. Snapd status is "in progress" though.

**Comment by jans23** [comment]
Note that Nitrokey App 1.3 is available as AppImage.

**Comment by 4jNsY6fCVqZv** [comment]
Hi, this is a very old issue I see. But for me it has great relevance. My current Linux distro is thinking about preferring flatpaks as sources. Could you imagine providing Flatpaks and sharing them on https://flathub.org/ for example?

**Comment by rugk** [comment]
Yeah…
same with [Fedora Silverblue](https://silverblue.fedoraproject.org/).

Flatpaks are a new software distribution mechanism for Linux distros, can thus installed on any distro and are easy to update. 

Here is [how to get started](http://docs.flatpak.org/en/latest/getting-started.html).

**Comment by enleth** [comment]
We've been working on Flatpak builds recently and the latest one seems to be working fine, so it has been added to the 1.4 release on GitHub: https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.4

Future releases will get Flatpak packages immediately.

We're hoping to release it on Flathub soon as well but Flatpak makes it just as easy to install a manually downloaded package, so you can get it right now and don't have to wait.

**Comment by 4jNsY6fCVqZv** [comment]
@enleth Thank you for your work! Will this Flatpak be officially created and maintained by Nitrokey when it appears on Flathub?

p.s. I read that the Nitrokey app communicates with udev. And I heard from the developers of another software that Flatpak can't handle udev and therefore their camera function doesn't work. How did you solve this?

**Comment by 4jNsY6fCVqZv** [comment]
@enleth  

> As soon as Flatpak introduces a method to allow access to specific devices, we'll use it to restrict the permissions, but right now this is the only way.

Have you opened a ticket for it in the Flatpak repository or can you do it so that it can be realized in the foreseeable future?

How critical do you see a --device=all permission for use in Nitrokey? Because you're all about security, aren't you?

**Comment by enleth** [comment]
> Have you opened a ticket for it in the Flatpak repository 

There is one: https://github.com/flatpak/xdg-desktop-portal/issues/227

> or can you do it so that it can be realized in the foreseeable future?

This is far too complex of an issue for an outside contributor to solve properly (or at all, I think).

> How critical do you see a --device=all permission for use in Nitrokey? Because you're all about security, aren't you?

That's not a serious question, is it? Obviously, the whole point of the Nitrokey App and the only reason to use it is to configure a USB device, so a way to access the device is critical. Also obviously, Nitrokey App doesn't need access to *all* devices, just USB devices with specific VID/PID pairs, so accessing *all* devices is completely unnecessary.

But all Flatpak offers now is `--device=all`, [the official documentation](http://docs.flatpak.org/en/latest/sandbox-permissions.html#device-access) confirms it, and the Flatpak developers [tell people to use that](https://github.com/flatpak/flatpak/issues/12#issuecomment-229921123) - that is, when they respond to such issues at all.

Honestly, I'm not sure what sort of answer you actually expected here.

**Comment by 4jNsY6fCVqZv** [comment]
> That's not a serious question, is it? 

Yes, it is. I'm interested in whether the use of these extended privileges can or will compromise my desired additional security through the Nitrokeys.
Because then I should consider whether I really want to install the Nitrokey App as Flatpak over Flathub. However, I cannot technically assess and judge this. That is why I am asking.

**Comment by enleth** [comment]
You mean as opposed to installing it using regular distribution repository?

The Flatpak privilege system defines restrictions - and restrictions _only_. The sandboxed application still runs under your user account and, in the end, is still just a normal POSIX process subject to normal system-wide permission checks. Flatpak's `device=all` does not mean "magically give this application run by a regular user FULL ACCCESS TO ALL THE DEVICES", it only means "do not impose extra device access restrictions on top of what this user account can do outside of Flatpak". There are no "extended" privileges in play here, at most it's "unrestricted".

Thus, at the moment, Nitrokey App Flatpak gets exactly as much device access as Nitrokey App installed as a DEB package, not a bit more.

I suppose Flatpak's naming for the privilege levels could be a bit better as to not be misleading in this manner.

**Comment by 4jNsY6fCVqZv** [comment]
There is problem with publishing via Flathub. Flathub is a platform that also offers proprietary packages. Since I switched to Linux to only find free software in my Software Center, installing the Nitrokey-App Flatpak unfortunately takes me away from this goal. When I install an app via Flathub, the proprietary apps I don't want are suddenly displayed in my Software Center. I don't want that. Therefore I ask you to offer an official version for download via your website as an alternative for people who are looking for 100% Free Software.

**Comment by szszszsz** [comment]
I think it is intended (to confirm) to be also distributed through Github releases, as here for v1.4: https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.4

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your answer! Does downloading via GitHub mean that the package will receive automatic updates via my Software Center as soon as there is a new release tag in your GitHub repository?

That leaves one point that worries me. GitHub uses Amazon Server to host the packages. Your website runs on servers of a small Berlin company. Would it be possible to offer an Amazon free download with a non-US server location?

**Comment by 4jNsY6fCVqZv** [comment]
I'm a little irritated about the Flatpak file in your release repo.
The name seems to be "nitrokey-app-1.4.0.flatpak".
My system doesn't recognize it as Flatpak. Different than with LibreOffice.
https://www.libreoffice.org/download/flatpak/
There the filename is LibreOffice.flatpakref. I would expect the file extension of the Nitrokey app to be similar to that of LibreOffice!

**Comment by alex-nitrokey** [comment]
If you want to have automatic update via the Software Center you need to install the App via your Software Center or install our ppa as explained [here](https://www.nitrokey.com/download/ubuntu).

If you do not want to or can not install it over the Software Center because of whatever reason, you can either install the flatpak via Flathub (as soon it is published there) or install the App via [snap](https://www.nitrokey.com/download/appimage-and-snap). Both possibilities provide automatic updates though not over the Software Center as far as I know.

If this also is not possible for you for whatever reason you need to update the App yourself. You can watch this repo for releases only and thus get informed about new releases. This applies for using the AppImage or installing the .deb file attached to every release.

**Comment by 4jNsY6fCVqZv** [comment]
@alex-nitrokey Thanks for your feedback! What can you tell me about your GitHub Flatpak file format?  "nitrokey-app-1.4.0.flatpak" doesn't seem to be valid. I would expect a "nitrokey-app-1.4.0.flatpakref" file. Flathub even looks a little different `flatpak install flathub com.domainname.appname`.

**Comment by alex-nitrokey** [comment]
As stated above, our App is not at Flathub yet (afaik). Thus, `flatpak install flathub ...` won't work. As far as I can see you can use `flatpak install <flatpakg-file>` where `<flatpak-file>` is the file found in our release page.

I can not tell you any more, as I am not using flatpak. If you have a specific technical problem with the flatpak file, please let us know. Otherwise, I kindly ask you to change to our [support forum](https://support.nitrokey.com/) as your questions may be of interest for other users as well and may are not development related.

> I am clearly concerned about ethical reasons! see above.

I proposed multiple solutions above which should be no problem regarding ethical considerations. Please choose the one you like most.

**Comment by 4jNsY6fCVqZv** [comment]
If you can set up your publishing system so that the Flatpak is available at https://www.nitrokey.com/download, that would be very supportive and a solution to my ethical dilemma!

Still, I have a problem with the Flatpak in your GitHub repo. https://github.com/Nitrokey/nitrokey-app/issues/114#issuecomment-555474534
My system doesn't recognize it as Flatpak. To my knowledge the file should end in .flatpakref. Can you please look for it?

**Comment by 4jNsY6fCVqZv** [comment]
The problem with the unrecognized Flatpak repo file still exists. Is there someone at Nitrokey or in the community who can check it?

**Comment by szszszsz** [comment]
Hi!
I am sorry this takes so long. Indeed the Gnome Software is not working with this file directly, thus confusing the user. This should be fixed on the next release at most (hopefully earlier). In the meantime please use command line interface to install the application. I have made a quick demo using it here:
- https://asciinema.org/a/Lpe06tnkkBjVujQdoBHSJ49Xg

**Comment by rugk** [comment]
Hmm, still confused. This just shows the uninstallation. The flatpak is still alos not available on Flathub.org, and I also cannot find it on https://www.nitrokey.com/download, so hmm... 
So at least a self-hosted flatpak repo would be great for automatic updates, or (or "and") publishing it on the existing Flathub infrastructure.

**Comment by 4jNsY6fCVqZv** [comment]
@rugk As I see the video, both the installation and the uninstallation process are addressed. 
What concerns me: What exactly is the source of the installation? Is it hosted by Nitrokey itself and the Flatpak distributed over it?
@szszszsz What does it take to fix this? Would a point release be possible?

**Comment by 4jNsY6fCVqZv** [comment]
@rugk As I see the video, both the installation and the uninstallation process are addressed. 

@szszszsz  Thanks for getting your feedback! What concerns me:
1. What exactly is the source of the installation? Is it hosted by Nitrokey itself and the Flatpak distributed over it?
2. What does it take to fix this?
3. Would a point release be possible?

**Comment by szszszsz** [comment]
Connected: https://github.com/flathub/flathub/pull/2081

**Comment by szszszsz** [comment]
Hi @4jNsY6fCVqZv! Sorry for the delay.

The binary we have on Github release page right now is built by us, however it is not easily discoverable by the GNOME Software. We have applied to Flathub for that, which compiles and distributes the binaries by itself.
If one wants to use the binary built by us, then it needs to be downloaded by hand and installed using CLI at the moment. If there would be a demand, perhaps we could offer own Flatpak repo (idea to discuss).

cc @daringer

**Comment by daringer** [comment]
Good news, the nitrokey-app is now available via the official flathub repository: https://flathub.org/apps/details/com.nitrokey.nitrokey-app

closing this issue, feel free to open a new one if you encounter issues...

**Comment by 4jNsY6fCVqZv** [comment]
@szszszsz @daringer Thanks for working on Flatpak support!

> If one wants to use the binary built by us, then it needs to be downloaded by hand and installed using CLI at the moment. If there would be a demand, perhaps we could offer own Flatpak repo (idea to discuss).

For our company, this is still a current concern yes. Would you like to have a new issue for discussion? Then I will open one.

**Comment by szszszsz** [comment]
@4jNsY6fCVqZv Please make a new one if possible, thank you!
