### ISSUE TITLE
Hidden volume is volatile

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#28]
See [#167 at Assembla](https://www.assembla.com/spaces/cryptostick/tickets/167-hidden-volume-is-volatile/details#)

**Comment by szszszsz** [comment]
Copied details:

> 
> Ubuntu 14.04
> 
> The hidden volume's contents doesn't seem to be saved.
> 
> Replicate:
> 1) Unlock hidden volume.
> 2) Create a folder and a file inside the new folder
> 3) Then lock hidden volume
> 4) Again unlock the hidden volume. The folder should exist, but not the file in it.
> 
> Idee: GUI sollte Sync anstoßen oder Hinweis an den User, dass er unmounted.
> Wie man die richtige Partition herausfinden könnte: https://unix.stackexchange.com/questions/80875/find-out-if-a-specific-device-is-an-usb-mass-storage

**Comment by szszszsz** [comment]
Issue was registered on Ubuntu 14.04. Tested on Ubuntu 15.04. MacOS should not be affected (but it will be tested in the end).

**Comment by szszszsz** [comment]
Application now has a nice feature of waiting until transfer is completed 
while trying to switch between the volumes during file transfer. It could be also 
considered as bug since it does not offer forcing of the unmount. This should be 
resolved in separate issue.

By tests I mean running following scenarios multiple times:
- Test 1 Run application in debug mode and watch debug messages is unmount successful
1. Unlock encrypted volume
1. Unlock hidden volume
1. Unlock encrypted volume
1. Lock device
1. Unlock encrypted volume
1. Unlock hidden volume
1. Lock volume
- Test 2 Switch encrypted to hidden volume during file transfer and vice-versa
1. Unlock encrypted volume
1. Start copy video file to encrypted volume
1. Unlock hidden volume
1. Start copy video file to hidden volume
1. Unlock encrypted volume
1. Seek movie, check is it watchable in the middle and the end
1. Unlock hidden volume
1. Seek movie, check is it watchable in the middle and the end

**Comment by szszszsz** [comment]
It should be checked whether this bug occurs on Mac
