### ISSUE TITLE
UDEV rule included in Debian package, please note this on instructions

### ISSUE THREAD

**Issue by kitterma** [Nitrokey/nitrokey-app#317]
- Application version: nitrokey-app 1.2.1
- Operating system: Debian 9 (Stretch) Linux l5580 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
- Device model and firmware version: Pro v0.8
- Connected USB port type: unknown
- Issue occurrency: always

The nitrokey-app package as shipped by Debian includes the UDEV rule, so if installing from official Debian packages, the note about needing to manually add the rule is incorrect:

https://www.nitrokey.com/documentation/installation#p:nitrokey-pro&os:linux

I couldn't tell where to file issues against the nitrokey-app web site material, so please reassign as needed.

**Comment by techge** [comment]
You are totally right. This is true for many distros now, but wasn't in the past. Because of the lack of a full overview I let it there until now, but I plan to change this in future and make sure to note, that the udev rules are only needed if it is not working automatically.

Thanks for noting!

**Comment by szszszsz** [comment]
By the way, the udev rule is planned to be moved to libnitrokey's package from next release (since it needs it as well).

**Comment by szszszsz** [comment]
@techge Please close this once done. Thanks!

**Comment by alex-nitrokey** [comment]
Sorry for the delay!
Okay I have overlooked the ugly instructions of the website. Stuff regarding ccid shouldn't be needed anymore, as nearly every recent distribution should have ccid > 1.4.21 where Nitrokey got included anyway. I will put it in Troubleshooting in case anyone still has a problem.

As for the udev rules I got a bit confused: are they only needed when using the App or even for GnuPG functions? In other words: can we just tell users to either install the App or including the rules by themselves or can we rather just skip talking about udev rules at all because the user either needs App and installs it or does not need the rules? 

I guess the user needs the rules one way or the other... If so: scdaemon now includes the rules as well and can be used to get them? Or is it my head which plays games with me? I thought I read something like this... This would make it easier for the instruction (install ccid and scdaemon)

**Comment by alex-nitrokey** [comment]
May I add: Since which version of the App the rules are included?

**Comment by szszszsz** [comment]
I think that it was in package from the very beginning (v0.2).

**Comment by alex-nitrokey** [comment]
Well we have the udev message there for Pro and Storage only. Average user will want to install the App for these devices anyway. Therefore I would say we should really delete this udev notice and only have a entry in troubleshooting. I will do so next week.

**Comment by szszszsz** [comment]
Sorry, I have missed your other question. Udev rules are needed for any user access to the listed hardware. GnuPG (scdaemon) has its own udev rules with our devices included (all if I am not mistaken). Nitrokey App has also provided udev rules until recently (it has been moved to libnitrokey, where it is needed anyway).
Generally note about the rules was needed for earlier GnuPG (since it wasn't packaged with them) but it might not be needed now for most distributions. Perhaps it would be good to compile the guide with advises like the udev notice, in case it would not be packaged correctly on some distribution.

**Comment by alex-nitrokey** [comment]
Okay, I removed the udev-rules notice. This is fixed imho. The instructions are now much more smaller...

**Comment by jans23** [comment]
@alex-nitrokey Can this be closed?

**Comment by alex-nitrokey** [comment]
Yes indeed, can't do myself...

**Comment by szszszsz** [comment]
I see, I thought you had the privileges (especially once you were assigned).
Closing it then. Thank you!
