### ISSUE TITLE
Your GPG Key (D9BAE35991DE5B22) is invalid since 2017.01.18

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-app#327]
As title say, the official Nitrokey GPG key is invalid since more then one month now.

You should fix this with a new key and use this new key for Github signing or at least, renew the key

**Comment by szszszsz** [comment]
Hi @beerisgood !
I have extended it on the day before it was meant to expire (2018.01.10).
You can confirm its state on a [key server, like pgp.mit.edu](https://pgp.mit.edu/pks/lookup?op=vindex&search=0xD9BAE35991DE5B22).
To update local key database it should be sufficient to run:
```
gpg --refresh-keys
```

Thank you for the alertness nevertheless!

--
Closing as invalid, since issue is related to packaging.
