### ISSUE TITLE
Improve usability of hidden volume setup form

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#72]
List:
- [x] improve general elements layout
- [ ] add more help description (what is 'entropy' rank?  what password should be chosen?  chars range for password, hidden slots description,  how possible hidden volume size is changing in regard of partition type of encrypted volume or its available free space?  could hidden volume be overwritten by data from encrypted volume?) 
- [x] fix tab jumps between fields
- [x] improve password input and entropy information

**Comment by jans23** [comment]
See also the [old ticket](https://app.assembla.com/spaces/cryptostick/tickets/179-safe-creation-of-hidden-volumes-without-corrupting-encrypted-volume/details#).

**Comment by szszszsz** [comment]
Old ticket suggestions:
- [ ] Check maximum password field length
- [ ] Use MB instead of percentages
- [ ] Position hidden volume at the end of free space
- [ ] Inform how much password entropy is safe
- [ ] Add instructions on top of the dialog

**Comment by jans23** [comment]
@szszszsz Let me know if you need more specific information or want some feedback on your solution.

**Comment by szszszsz** [comment]
Hi @jans23 !
Could you please then check solution on branch `issue_72-hidden_setup_usability` and give feedback?
Adding more instructions (regarding password real strength and hidden volume characteristics) would need to move from window form to setup wizard. Would you like it to do so?
Is default position (70-90%) of hidden volume acceptable?

**Comment by szszszsz** [comment]
Wizard might be done separately and run only if user wish for it (so experienced user would not have to go all the way with wizard forms and had all on one page)

**Comment by jans23** [comment]
"Use MB instead of percentages" shouldn't be checked yet, right? At lest for me its still displayed in percentage.

The window has some problems. See: ![hidden volume setup](https://cloud.githubusercontent.com/assets/1450547/17625508/87e8bf56-60a9-11e6-87e8-2f28dc398b52.png)

I suggest to add a big disclaimer on top of the window. For instance: "You should understand the properties of hidden volumes before proceeding. Please read [these instructions](https://www.nitrokey.com/documentation/hidden-volumes).

**Comment by szszszsz** [comment]
Interesting. What OS do you use?
It looks like this on my side:
![hidden volume window correct](https://cloud.githubusercontent.com/assets/17005426/17627362/48bebfee-60b1-11e6-94c5-8ec1347f2fea.png)

**Comment by jans23** [comment]
Ubuntu 16.04 with Unity. The App is compiled with qmake.

**Comment by szszszsz** [comment]
I have designed the form with rescaled down desktop (with factor 0.75) and this is the cause of different view. I will check factor 1.0.

**Comment by szszszsz** [comment]
Fixed. Please check latest commit.

**Comment by jans23** [comment]
Yes, now the window looks correct and very nice!

Here are a few more suggestions:
- Disclaimer at the top: Please make it **bold**. In the "About" window we use a triangular warning icon. Perhaps put it left from the disclaimer.
-  Change disclaimer to "You should understand the properties of hidden volumes before proceeding. It can destroy your encrypted data! Please read these instructions first."
- Add instructions below the disclaimer: "1. You may want to copy some innocuous files to the encrypted data. 2. Configure hidden volumes in this dialogue. 3. Once you configured a hidden volume you must not use/write to the encryption volume anymore. Otherwise it may destroy the data in your hidden volume."
- Suggestion for the text: "Start/End hidden volume at <INPUT FIELD> %/MB/GB of the encrypted storage
- "SD size" -> "Storage capacity"
- I don't understand the last sentence ("Size will be rounded..."). Perhaps remove it?
- Perhaps remove the lines "Entropy guess..." and "using human..." ?
- Is "10% and 90%" static text or where do those values come from?

**Comment by szszszsz** [comment]
The 10% and 90% are hardcoded values. I guess these are set to omit filesystem structures.
As for `Size will be rounded` - hidden volume creation command has in its parameters size given in integral percent, thus final size will be rounded down to multiplicity of 1% of storage size.

**Comment by szszszsz** [comment]
Please check latest commit.

**Comment by szszszsz** [comment]
Hi @jans23 !
Is the current solution acceptable?

**Comment by szszszsz** [comment]
Please request further improvements in new issue
