### ISSUE TITLE
No factory reset option available 

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#80]
According to https://www.nitrokey.com/documentation/frequently-asked-questions#how-to-reset-a-nitrokey in admin mode there should be a factory reset ("factory settings") option, but it is not shown:

> 
> Option 1, if the device is not locked and if you remember the valid Admin PIN use Nitrokey App:
> Open a terminal (on Windows: Press the Start button and enter "cmd") and start the Nitrokey App with "nitrokey-app --admin". Klick on the Nitrokey App's tray icon, select "Configuration" and "factory settings".

Nitrokey Storage, 0.31
Nitrokey App, 6c468335ea6054baf0bfbe9416f2546aae1926f8
Ubuntu 16.04

**Comment by jans23** [comment]
Correct, the App doesn't contain this function. I updated the FAQ accordingly. Currently I don't see a use case for a factory reset in the NK App. Please let me know otherwise. In this case we should rethink that the Admin PIN is required (see below).

To clarify the firmware's functionality: The NK Storage firmware has a factory reset implemented already (eventhough its not available in the App). It is command 0x13 and requires the Admin PIN. What it does is:

1. Reset the OpenPGP Card
1. Overwrite the user page with random numbers, delete it and set default parameters
1. Deactivate firmware update mode (just in case)
1. Checks if SD card is new or not
1. Overwrite the password safe and OTP slots with random numbers and delete it afterwards
1. Overwrite the hidden volume descriptor table with random numbers and delete it afterwards
1. Set the Update Password to default

Note that it doesn't flash a new firmware which would be required during manufacturing process. 
For a reset in the factory we should perform the following steps instead:

1. Reset the OpenPGP Card
1. Perform a chip erase (this has the same effect as all the separate steps above)
1. Flash new firmware
1. Format the unencrypted volume, create new partitions and copy the files-to-be-shipped to it
